apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus.fullname" . }}-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus.fullname" . }}-v2
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus.fullname" . }}
    namespace: {{ .Release.Namespace }}
