apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    app: prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      serviceAccountName: {{ include "prometheus.fullname" . }}
      containers:
        - name: prometheus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--storage.tsdb.path=/data"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention={{ .Values.retention }}"
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /data
            - name: rules
              mountPath: /etc/prometheus/rules
      volumes:
        - name: config
          configMap:
            name: {{ include "prometheus.fullname" . }}

        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "prometheus.fullname" . }}
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}

        - name: rules
          configMap:
            name: {{ include "prometheus.fullname" . }}-rules
