apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    app: prometheus
spec:
  type: {{ if .Values.service.enableNodePort }}NodePort{{ else }}{{ .Values.service.type }}{{ end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9090
      {{- if .Values.service.enableNodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: prometheus
