apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: kube-state-metrics
  ports:
    - name: http-metrics
      port: {{ .Values.service.port }}
      targetPort: 8080
